---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: Cron-job
  labels:
    topic: CronJobs
spec:
  jobTemplate:
    - metadata:
        name: Cron-job
      spec:
        template:
          metadata:
            name: Cron-job
          spec:
            containers:
              - name: Cron-job
                image: alpine:3
                command:
                  - "sleep"
                  -  "10s"
  schedule: "*/5****"



