---
apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  containers:
    - name: init-container
      image: jenkins/jenkins:lts
      ports:
        - containerPort: 8080
  initContainers:
    - name: init-api-service
      image: alpine:3
      command: ["sleep", "5s"]
    - name: init-db-service
      image: alpine:3
      command: ["sleep", "5s"]