---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    version: "1.23.0"
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: "1.23.0"
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: "1.23.0"
    spec:
      - containers:
        - image: nginx:1.23.0
          name: nginx
          ports:
            - containerPort:80
